baseURL: ""
languageCode: en-us
title: ariana's blog
theme: PaperMod
math: true
markup:
  goldmark:
    renderer:
      unsafe: true

params:
  env: production
  math: true
  enableEmoji: true
  katexPath : "katex"
  homeInfoParams:
    Title: "a blog about research, art and life ðŸ’‹"
    Content:
      - i'm over here doing what i like,*
        i'm over here working day and night.*
        if my real ain't real enough,*
        i don't know what is.
        # - say i don't know what i'll do without you in my life.* 
        # it'd be so sour.*
        # i'm hoping that everybody can experience, what we have in ours.*
      - hey, what happened to the butterflies?
      - imagine a world like that.
        # - couldn't ever imagine even having doubt,* 
        # but, not everything works out.
        # - down like six thirty (yuh), down like sunset (hmm)
      - say it's tricky at the top,*
        gotta have a slim ego for a thick wallet.
      - if i were you, i'd wanna be me too.*
        #      - so long as i live, i love u, will have and hold you.*
        #you look so beautiful in white.*
        #what we have is timeless, my love is endless.*
        #with all my heart, i mean every word.
      - say i don't know what i'll do without u in my life, but it'd be so sour.*
        i'm hopin that everybody can experience what we have in ours.*
      - treat my goals like properties*
        collect them like monopoly
      - I like the idea of craziness with discipline.*
        â€”â€” Karl Lagerfeld
  # social:
  #   - name: "Instagram"
  #     url: "https://www.instagram.com/lovefromarianatang/"
              
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    # limit: 10 # refer: https://www.fusejs.io/api/methods.html#search
    keys: ["title", "permalink", "summary", "content"]


outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary

menu:
  main:
    #- identifier: tags
    #  name: tags
    #    # url: posts/tags
        #  weight: 10
    - identifier: tags
      name: tags
      url: posts/tags
      weight: 10
      #  url: /tags/
    - name: archive
      url: archives
      weight: 10
    - name: search
      url: /search
      weight: 1
    - name: about me
      url: /about
      weight: 11
    # - name: pending ideas
    #   url: /procrastination_bulletin
    - name: "random"
      pageRef: "/random"
      weight: 99

